name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Haciendo el checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        patch_pattern: "fix:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
  
    - name: Login en DockerHub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando el login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Finalizando el login"

    - name: Build docker image on cloud
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build --tag reaperjc/graph-ql:$NEW_VERSION .
        docker build --tag reaperjc/graph-ql:latest .

    - name: Push docker image to docker hub
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push reaperjc/graph-ql:$NEW_VERSION
        docker push reaperjc/graph-ql:latest

        
   # - name: Build the Docker image
   #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
